accordion commit
js-tasks-ru/htmlcss-20230411_gstratiyj pull request #5
Opened 2023-04-24 08:18 UTC by glebstratiy

2023-04-24 08:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 19:50 UTC, GSemikozov requested changes

2023-04-24 19:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +:root {
root задаем лишь раз на глобальном уровне, в нашем случае в main.css

2023-04-24 19:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
лишнее ограничение

2023-04-24 19:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__title__arrow {
.accordion__title__arrow -> .accordion__title-arrow

2023-04-24 19:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    right: 1100px;
точно ли? пока не изучали тему позиционирование, советую стрелку просто не добавлять

2023-04-24 19:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: #495057;
не хватает других свойств - font-family, font-weight, line-height

2023-04-25 12:02 UTC, GSemikozov approved these changes

2023-04-25 12:02 UTC, merged